In [1]:
import pandas as pd
import numpy as np

from MATRIX.models import BaseSurvival, CoxRegression, DeepSurv, RandomSurvForest, DeepMultiTask, CoxRegressionWithTimeVarying, DeepTimeVarying
from MATRIX.utils import get_data, get_metrics, get_results, get_xai, save_results

# Experiments

## Survival analysis (standard)

### Get data

In [2]:
X_train_standard, y_train_standard, X_validation, y_validation, X_test, y_test, feature_names, scaler = get_data(dataset_name="colon.csv")

- - - - colon.csv (csv) - - - -

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   event         911 non-null    int64
 1   time          911 non-null    int64
 2   num_age       911 non-null    int64
 3   num_nodes     911 non-null    float64
 4   fac_rx        911 non-null    object
 5   fac_sex       911 non-null    int64
 6   fac_differ    911 non-null    object
 7   fac_obstruct  911 non-null    int64
 8   fac_perfor    911 non-null    int64
 9   fac_adhere    911 non-null    int64
 10  fac_node4     911 non-null    int64
dtypes: float64(1), int64(8), object(2)
memory usage: 78.4+ KB

             event         time     num_age   num_nodes fac_rx     fac_sex  \
count   911.000000   911.000000  911.000000  911.000000    911  911.000000
unique         NaN          NaN         NaN         NaN      3         NaN
top            NaN          NaN         NaN         NaN    Obs         NaN
freq           NaN          NaN         NaN         NaN    312         NaN
mean      0.484083  1675.373216   59.777168    3.659715    NaN    0.522503
std       0.500021   869.692766   11.885616    3.572562    NaN    0.499768
min       0.000000    23.000000   18.000000    0.000000    NaN    0.000000
25%       0.000000   821.500000   53.000000    1.000000    NaN    0.000000
50%       0.000000  1981.000000   61.000000    2.000000    NaN    1.000000
75%       1.000000  2370.000000   69.000000    5.000000    NaN    1.000000
max       1.000000  3329.000000   85.000000   33.000000    NaN    1.000000

       fac_differ  fac_obstruct  fac_perfor  fac_adhere   fac_node4
count         911    911.000000  911.000000  911.000000  911.000000
unique          4           NaN         NaN         NaN         NaN
top             2           NaN         NaN         NaN         NaN
freq          653           NaN         NaN         NaN         NaN
mean          NaN      0.193194    0.029638    0.144896    0.261251
std           NaN      0.395021    0.169679    0.352189    0.439558
min           NaN      0.000000    0.000000    0.000000    0.000000
25%           NaN      0.000000    0.000000    0.000000    0.000000
50%           NaN      0.000000    0.000000    0.000000    0.000000
75%           NaN      0.000000    0.000000    0.000000    1.000000
max           NaN      1.000000    1.000000    1.000000    1.000000

### Instantiate models

In [3]:
modelCoxRegression = CoxRegression()
modelRandomSurvForest = RandomSurvForest(0)
modelDeepSurv = DeepSurv(X_train_standard.shape[1])

### Fit and predict

In [4]:
modelCoxRegression = modelCoxRegression.fit(X_train_standard, y_train_standard)
modelRandomSurvForest = modelRandomSurvForest.fit(X_train_standard, y_train_standard)
modelDeepSurv = modelDeepSurv.fit(X_train_standard, y_train_standard)

survPredCoxRegression = modelCoxRegression.predict(X_test)
survPredRandomSurvForest = modelRandomSurvForest.predict(X_test)
survPredDeepSurv = modelDeepSurv.predict(X_test)

### Metrics

In [5]:
get_metrics([y_train_standard, y_test], [survPredCoxRegression])

{'C-Index Harrel': 0.6011437635665386,
 'C-Index IPCW': 0.6102418142329669,
 'Cumulative Dinamic AUC': [0.5832670650305211,
  0.6284814887997692,
  0.6584076144438055]}

In [6]:
get_metrics([y_train_standard, y_test], [survPredRandomSurvForest])

{'C-Index Harrel': 0.5958841208882952,
 'C-Index IPCW': 0.598702568660489,
 'Cumulative Dinamic AUC': [0.5788004074123053,
  0.6242527737906206,
  0.6542207854260769]}

In [7]:
get_metrics([y_train_standard, y_test], [survPredDeepSurv])

{'C-Index Harrel': 0.46873434630155286,
 'C-Index IPCW': 0.44796871536857497,
 'Cumulative Dinamic AUC': [0.474992488625633,
  0.43369477801024414,
  0.4333897780332707]}

### Survival / Cumulative Hazard Functions

In [ ]:
survival_function = modelCoxRegression.predict_survival_function(X=X_train_standard, estimator_name="modelCoxRegression", dataset="colon.csv", seed=0, plot=False)

In [ ]:
cumulative_hazard_function = modelCoxRegression.predict_cumulative_hazard_function(X=X_train_standard, estimator_name="modelCoxRegression", dataset="colon.csv", seed=0, plot=False)

### eXplainable Artificial Intelligence

In [ ]:
modelCoxRegression.calculate_xai(X=X_train_standard, estimator_name="modelCoxRegression", dataset="colon.csv", seed=None, feature_names=feature_names, background=50, plot=False)

## Survival analysis (multitask)

### Get data

In [11]:
X_train, y_train, X_validation, y_validation, X_test, y_test, feature_names, scaler = get_data(dataset_name="colon.csv", to_multitask=True)

- - - - colon.csv (csv) - - - -

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   event         911 non-null    int64
 1   time          911 non-null    int64
 2   num_age       911 non-null    int64
 3   num_nodes     911 non-null    float64
 4   fac_rx        911 non-null    object
 5   fac_sex       911 non-null    int64
 6   fac_differ    911 non-null    object
 7   fac_obstruct  911 non-null    int64
 8   fac_perfor    911 non-null    int64
 9   fac_adhere    911 non-null    int64
 10  fac_node4     911 non-null    int64
dtypes: float64(1), int64(8), object(2)
memory usage: 78.4+ KB

             event         time     num_age   num_nodes fac_rx     fac_sex  \
count   911.000000   911.000000  911.000000  911.000000    911  911.000000
unique         NaN          NaN         NaN         NaN      3         NaN
top            NaN          NaN         NaN         NaN    Obs         NaN
freq           NaN          NaN         NaN         NaN    312         NaN
mean      0.484083  1675.373216   59.777168    3.659715    NaN    0.522503
std       0.500021   869.692766   11.885616    3.572562    NaN    0.499768
min       0.000000    23.000000   18.000000    0.000000    NaN    0.000000
25%       0.000000   821.500000   53.000000    1.000000    NaN    0.000000
50%       0.000000  1981.000000   61.000000    2.000000    NaN    1.000000
75%       1.000000  2370.000000   69.000000    5.000000    NaN    1.000000
max       1.000000  3329.000000   85.000000   33.000000    NaN    1.000000

       fac_differ  fac_obstruct  fac_perfor  fac_adhere   fac_node4
count         911    911.000000  911.000000  911.000000  911.000000
unique          4           NaN         NaN         NaN         NaN
top             2           NaN         NaN         NaN         NaN
freq          653           NaN         NaN         NaN         NaN
mean          NaN      0.193194    0.029638    0.144896    0.261251
std           NaN      0.395021    0.169679    0.352189    0.439558
min           NaN      0.000000    0.000000    0.000000    0.000000
25%           NaN      0.000000    0.000000    0.000000    0.000000
50%           NaN      0.000000    0.000000    0.000000    0.000000
75%           NaN      0.000000    0.000000    0.000000    1.000000
max           NaN      1.000000    1.000000    1.000000    1.000000

### Instantiate models

In [12]:
modelDeepMultiTask = DeepMultiTask(X_train.shape[1])

### Fit and predict

In [13]:
modelDeepMultiTask = modelDeepMultiTask.fit(X_train, y_train)
survPredDeepMultiTask, binPredDeepMultiTask = modelDeepMultiTask.predict(X_test)

### Metrics

In [14]:
get_metrics([y_train, y_test], [survPredDeepMultiTask, binPredDeepMultiTask])

{'C-Index Harrel': 0.5150692937051261,
 'C-Index IPCW': 0.5077993684864526,
 'Cumulative Dinamic AUC': [0.5164806513956655,
  0.5102703562503049,
  0.5331083440800005],
 'MAE': 0.5191256830601093,
 'AMAE': 0.5191256830601093,
 'MS': 0.16939890710382513,
 'CCR': 0.4808743169398907,
 'RECALL0': 0.3114754098360656,
 'RECALL1': 0.16939890710382513}

### Survival / Cumulative Hazard Functions

In [15]:
survival_function = modelDeepMultiTask.predict_survival_function(X=X_train, estimator_name="modelDeepMultiTask", dataset="colon.csv", seed=0, plot=False)

In [16]:
cumulative_hazard_function = modelDeepMultiTask.predict_cumulative_hazard_function(X=X_train, estimator_name="modelDeepMultiTask", dataset="colon.csv", seed=0, plot=False)

### eXplainable Artificial Intelligence

In [17]:
modelDeepMultiTask.calculate_xai(X=X_train, estimator_name="modelDeepMultiTask", dataset="colon.csv", seed=0, feature_names=feature_names, background=50, plot=False)

## Survival analysis (time varying)

In [2]:
df = pd.read_csv("./MATRIX/datasets/colon.csv")

### Find splits dynamically

In [4]:
splits = BaseSurvival.dinamic_discretise(y=df[["time", "event"]], dataset="colon", seed=0, plot=False)

In [5]:
df["identifier"] = df.index.values

### Transform to time varying format

In [6]:
df = BaseSurvival.to_time_dependent(dataframe=df, splits=splits, identifier="identifier", time="time", event="event")

In [9]:
df = BaseSurvival.to_time_varying(dataframe=df, identifier="identifier", time="time", event="event")

### Get data

In [23]:
X_train, y_train, X_validation, y_validation, X_test, y_test, feature_names, scaler = get_data(df=df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4049 entries, 0 to 4048
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   identifier    4049 non-null   int64
 1   num_age       4049 non-null   int64
 2   num_nodes     4049 non-null   float64
 3   fac_rx        4049 non-null   object
 4   fac_sex       4049 non-null   int64
 5   fac_differ    4049 non-null   object
 6   fac_obstruct  4049 non-null   int64
 7   fac_perfor    4049 non-null   int64
 8   fac_adhere    4049 non-null   int64
 9   fac_node4     4049 non-null   int64
 10  event         4049 non-null   int64
 11  time_start    4049 non-null   float64
 12  time_stop     4049 non-null   float64
dtypes: float64(3), int64(8), object(2)
memory usage: 411.4+ KB

         identifier      num_age    num_nodes   fac_rx      fac_sex  \
count   4049.000000  4049.000000  4049.000000     4049  4049.000000
unique          NaN          NaN          NaN        3          NaN
top             NaN          NaN          NaN  Lev+5FU          NaN
freq            NaN          NaN          NaN     1379          NaN
mean     441.193628    59.653001     3.311929      NaN     0.521857
std      260.928141    11.765952     3.281244      NaN     0.499584
min        0.000000    18.000000     0.000000      NaN     0.000000
25%      216.000000    53.000000     1.000000      NaN     0.000000
50%      433.000000    61.000000     2.000000      NaN     1.000000
75%      664.000000    68.000000     4.000000      NaN     1.000000
max      910.000000    85.000000    33.000000      NaN     1.000000

       fac_differ  fac_obstruct   fac_perfor   fac_adhere    fac_node4  \
count        4049   4049.000000  4049.000000  4049.000000  4049.000000
unique          4           NaN          NaN          NaN          NaN
top             2           NaN          NaN          NaN          NaN
freq         2973           NaN          NaN          NaN          NaN
mean          NaN      0.179797     0.029637     0.137071     0.215609
std           NaN      0.384066     0.169605     0.343965     0.411295
min           NaN      0.000000     0.000000     0.000000     0.000000
25%           NaN      0.000000     0.000000     0.000000     0.000000
50%           NaN      0.000000     0.000000     0.000000     0.000000
75%           NaN      0.000000     0.000000     0.000000     0.000000
max           NaN      1.000000     1.000000     1.000000     1.000000

              event   time_start    time_stop
count   4049.000000  4049.000000  4049.000000
unique          NaN          NaN          NaN
top             NaN          NaN          NaN
freq            NaN          NaN          NaN
mean       0.108916   649.715239  1026.663868
std        0.311572   635.900022   757.642617
min        0.000000     0.000001    23.000000
25%        0.000000   272.500000   454.500000
50%        0.000000   454.500000  1000.500000
75%        0.000000  1000.500000  1364.500000
max        1.000000  2274.500000  3329.000000

### Instantiate models

In [24]:
modelCoxRegressionWithTimeVarying = CoxRegressionWithTimeVarying()
modelDeepTimeVarying = DeepTimeVarying(X_train.shape[1])

### Fit and predict

In [25]:
modelCoxRegressionWithTimeVarying = modelCoxRegressionWithTimeVarying.fit(X_train, y_train)
modelDeepTimeVarying = modelDeepTimeVarying.fit(X_train, y_train)

survPredCoxRegressionWithTimeVarying = modelCoxRegressionWithTimeVarying.predict(X_test)
survPredDeepTimeVarying = modelDeepTimeVarying.predict(X_test)

### Metrics

In [26]:
get_metrics([y_train, y_test], [survPredCoxRegressionWithTimeVarying])

{'C-Index Harrel': 0.6706086623646506,
 'C-Index IPCW': 0.6585322447399417,
 'Cumulative Dinamic AUC': [0.6770340633108334,
  0.6695773476164759,
  0.6192424454026013]}

In [27]:
get_metrics([y_train, y_test], [survPredDeepTimeVarying])

{'C-Index Harrel': 0.5069452039811878,
 'C-Index IPCW': 0.5101314470110674,
 'Cumulative Dinamic AUC': [0.46800686588479573,
  0.5522360203619334,
  0.5214476025548159]}

### Survival / Cumulative Hazard Functions

In [28]:
survival_function = modelCoxRegressionWithTimeVarying.predict_survival_function(X=X_train, estimator_name="modelCoxRegressionWithTimeVarying", dataset="colon.csv", seed=0, plot=False)

In [29]:
cumulative_hazard_function = modelCoxRegressionWithTimeVarying.predict_cumulative_hazard_function(X=X_train, estimator_name="modelCoxRegressionWithTimeVarying", dataset="colon.csv", seed=0, plot=False)

### eXplainable Artificial Intelligence

In [30]:
modelCoxRegressionWithTimeVarying.calculate_xai(X=X_train, estimator_name="modelCoxRegressionWithTimeVarying", dataset="colon.csv", seed=0, feature_names=feature_names, background=50, plot=False)

## Tools

### Feature selector

In [23]:
features_selected = BaseSurvival.feature_selection(X_train_standard, y_train_standard)

In [34]:
print(f"ALL FEATURES: {X_train_standard.shape}, SELECTED FEATURES: {X_train_standard[:, features_selected].shape}")

ALL FEATURES: (582, 6), SELECTED FEATURES: (582, 4)

### Simulated survival data

In [39]:
BaseSurvival.generate_simulated_survival_data(number_rows=1000, number_columns=10, censored=0.75, relation="sin", seed=0)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,event,time
0,1.764052,0.400157,0.978738,2.240893,1.867558,-0.977278,0.950088,-0.151357,-0.103219,0.410599,0,7.39
1,0.144044,1.454274,0.761038,0.121675,0.443863,0.333674,1.494079,-0.205158,0.313068,-0.854096,1,82.31
2,-2.552990,0.653619,0.864436,-0.742165,2.269755,-1.454366,0.045759,-0.187184,1.532779,1.469359,1,5.16
3,0.154947,0.378163,-0.887786,-1.980796,-0.347912,0.156349,1.230291,1.202380,-0.387327,-0.302303,1,3.00
4,-1.048553,-1.420018,-1.706270,1.950775,-0.509652,-0.438074,-1.252795,0.777490,-1.613898,-0.212740,0,2.93
...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.622801,1.240477,0.170446,1.986898,0.111301,1.209655,-0.457330,0.923183,1.325519,-0.953166,0,0.53
996,-0.678130,0.334100,-0.754928,-0.388383,-0.626576,-1.306421,-0.038496,0.143567,-0.789074,-0.098504,0,0.09
997,-1.452866,-0.947866,-0.869579,-0.305517,-0.605147,0.224821,-1.038472,0.771819,-0.480009,1.834745,0,0.06
998,-0.108765,0.454475,0.098709,-0.458305,-0.857044,-0.774403,0.708787,0.018474,-0.104081,-0.234858,0,0.33
999,-0.250906,-0.962750,0.493405,2.133050,0.983888,-1.809282,0.042359,0.516872,-0.032921,1.298111,0,3.49

### Log-rank test

In [11]:
identifier = np.arange(len(X_train_standard))

In [12]:
# H0 = "There is no difference in the survival curves between the groups analysed" (p-value < threshold ==> reject H0)
BaseSurvival.logrank_test(y_train_standard, identifier)

<lifelines.StatisticalResult: multivariate_logrank_test>
               t_0 = -1
 null_distribution = chi squared
degrees_of_freedom = 581
         test_name = multivariate_logrank_test

---
 test_statistic      p  -log2(p)
        3459.80 <0.005       inf

# Results

## Show stored results

In [5]:
results = get_results(estimator_name="CoxRegression", dataset="colon.csv")
#results = get_results(estimator_name="CoxRegressionWithTimeVarying", dataset="cgd.csv")
#results = get_results(estimator_name="DeepMultiTaskFFNN", dataset="colon.csv")

In [4]:
for i, result in enumerate(results):
    print(f"Result {i}:\n")
    print(f"    * Estimator: {result.config['estimator_name']} - Dataset: {result.config['dataset']} - Seed: {result.config['random_state']}")
    print(f"    * Best Params: {result.data_.best_params}")
    print()
    print(f"    * Metrics: {get_metrics(result.data_.targets, result.data_.predictions)}")
    print("\n\n")

Result 0:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 0
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6005593588245116, 'C-Index IPCW': 0.6171115091088967, 'Cumulative Dinamic AUC': [0.5790226380142177, 0.6288561402862889, 0.6565738162897639]}



Result 1:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 1
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6278135048231511, 'C-Index IPCW': 0.6344141780648662, 'Cumulative Dinamic AUC': [0.6651978973407545, 0.6484380362536082, 0.7288120768413935]}



Result 2:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 2
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6677913854869616, 'C-Index IPCW': 0.6438962832758339, 'Cumulative Dinamic AUC': [0.6921737644102026, 0.7141277809777058, 0.7134722573314778]}



Result 3:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 3
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6350244808374135, 'C-Index IPCW': 0.6230864550307337, 'Cumulative Dinamic AUC': [0.6324937887098537, 0.6416199821284245, 0.6837499364708751]}



Result 4:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 4
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6379959819186338, 'C-Index IPCW': 0.6252789145223887, 'Cumulative Dinamic AUC': [0.642915570814947, 0.6448861697123527, 0.6654813116655328]}



Result 5:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 5
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6431782235911097, 'C-Index IPCW': 0.6289157051841312, 'Cumulative Dinamic AUC': [0.6534313262823548, 0.6680947027318584, 0.6864735930209873]}



Result 6:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 6
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6659902261244098, 'C-Index IPCW': 0.6478996414736455, 'Cumulative Dinamic AUC': [0.727346903534666, 0.6981279781057307, 0.7180048096620617]}



Result 7:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 7
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6472841818491402, 'C-Index IPCW': 0.6527142606766461, 'Cumulative Dinamic AUC': [0.6965156794425087, 0.6682026739613727, 0.715769721331116]}



Result 8:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 8
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6140285071267817, 'C-Index IPCW': 0.6192946575089668, 'Cumulative Dinamic AUC': [0.5997910143616242, 0.6330738401997695, 0.6469794223932369]}



Result 9:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 9
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6168196994991653, 'C-Index IPCW': 0.6226970044403516, 'Cumulative Dinamic AUC': [0.6497342334506965, 0.6155312978642102, 0.6603343171935327]}



Result 10:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 10
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6229182202336565, 'C-Index IPCW': 0.6240552625282793, 'Cumulative Dinamic AUC': [0.640911298449101, 0.6252537673563415, 0.6637357992796512]}



Result 11:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 11
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6020542317173377, 'C-Index IPCW': 0.5987992828507005, 'Cumulative Dinamic AUC': [0.6500894956137924, 0.6265381543857446, 0.6298170201352357]}



Result 12:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 12
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6054101367122374, 'C-Index IPCW': 0.5875584122054305, 'Cumulative Dinamic AUC': [0.6219994079576875, 0.5966803234993022, 0.6443616017568569]}



Result 13:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 13
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6440713982150447, 'C-Index IPCW': 0.6175312357341921, 'Cumulative Dinamic AUC': [0.6487745098039216, 0.6869763777009644, 0.7262948325376563]}



Result 14:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 14
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6510670475550328, 'C-Index IPCW': 0.6823977972902846, 'Cumulative Dinamic AUC': [0.6443656909401791, 0.6818938642909946, 0.7496206402433708]}



Result 15:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 15
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6567349987550835, 'C-Index IPCW': 0.6382069190567802, 'Cumulative Dinamic AUC': [0.6829192084115578, 0.7073407882950039, 0.6643182677266659]}



Result 16:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 16
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6131925236778141, 'C-Index IPCW': 0.6062445937192372, 'Cumulative Dinamic AUC': [0.616418708932479, 0.6177263925127467, 0.6920739950212833]}



Result 17:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 17
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6084302082462156, 'C-Index IPCW': 0.5779823943349043, 'Cumulative Dinamic AUC': [0.6105542452830189, 0.6543129806574227, 0.637016847470315]}



Result 18:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 18
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.63595178719867, 'C-Index IPCW': 0.6378902453578756, 'Cumulative Dinamic AUC': [0.6814779661316945, 0.6568208132582332, 0.7005491645506672]}



Result 19:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 19
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6176372295095663, 'C-Index IPCW': 0.6139564213575359, 'Cumulative Dinamic AUC': [0.6203940157928889, 0.6644171431789049, 0.6728801519507368]}



Result 20:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 20
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6700186693822132, 'C-Index IPCW': 0.6615858539792441, 'Cumulative Dinamic AUC': [0.6925908521303258, 0.7397647622942728, 0.773337181253826]}



Result 21:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 21
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.5908019860304636, 'C-Index IPCW': 0.5836476632474129, 'Cumulative Dinamic AUC': [0.6694591904445919, 0.6206220079060253, 0.5862062800477793]}



Result 22:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 22
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6581897272879371, 'C-Index IPCW': 0.6381246176678695, 'Cumulative Dinamic AUC': [0.7407249961559058, 0.6617166692767491, 0.6374392049957562]}



Result 23:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 23
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6305252642970116, 'C-Index IPCW': 0.6257520318251958, 'Cumulative Dinamic AUC': [0.6407639968264297, 0.6639385502376275, 0.7152937847331546]}



Result 24:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 24
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6365983745343718, 'C-Index IPCW': 0.6368059280816305, 'Cumulative Dinamic AUC': [0.6310458969096666, 0.6700508069554318, 0.6520731108694704]}



Result 25:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 25
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6081803005008347, 'C-Index IPCW': 0.5983024211734403, 'Cumulative Dinamic AUC': [0.6795178505704821, 0.6223843063182859, 0.596814031863436]}



Result 26:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 26
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 0.1}

    * Metrics: {'C-Index Harrel': 0.6795159680638723, 'C-Index IPCW': 0.6832154271289738, 'Cumulative Dinamic AUC': [0.6739598102183476, 0.722194681705325, 0.7271348020182797]}



Result 27:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 27
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6144141893579815, 'C-Index IPCW': 0.6157451726912317, 'Cumulative Dinamic AUC': [0.6049050362909788, 0.6367883140033831, 0.6422779665226342]}



Result 28:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 28
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6380805469857417, 'C-Index IPCW': 0.6290271593670139, 'Cumulative Dinamic AUC': [0.6961699629167524, 0.66290385574341, 0.6688276402200679]}



Result 29:

    * Estimator: CoxRegression - Dataset: colon.csv - Seed: 29
    * Best Params: {'ties': 'efron', 'n_iter': 100, 'alpha': 10.0}

    * Metrics: {'C-Index Harrel': 0.6266309802609569, 'C-Index IPCW': 0.6011300055610743, 'Cumulative Dinamic AUC': [0.671743654561789, 0.6275168801487813, 0.6502672299775765]}

## Plot XAI results

In [7]:
get_xai(estimator_name="CoxRegression", dataset="colon.csv", seed=None, individual=0)
#get_xai(estimator_name="CoxRegression", dataset="colon.csv")
#get_xai(dataset="colon.csv")

## Save stored results

In [2]:
save_results(estimator_name="CoxRegression", dataset="aids2.csv")